# Generated by Django 2.2.4 on 2019-09-09 23:08

from django.db import migrations, models
import measurement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('top_left', measurement.models.CommaSeparatedFloatField(max_length=100)),
                ('bottom_right', measurement.models.CommaSeparatedFloatField(max_length=100)),
                ('direction', models.CharField(max_length=1)),
            ],
        ),
    ]
